### PR TITLE
CSV import

### PR DESCRIPTION
**Pull request by ilya-konanykhin**
There it goes!

```ruby
rake import:bikes:csv[import_file_name.csv,dry] # for a dry run, remove ",dry" to make a live run
```

Please try it out and let me know what you thinks. As always, comments are welcome.

### CODE REVIEW

**Comment by spacemunkay** [comment]
Awesome!  I'm really happy with the results.  

I did make a few changes locally in order to avoid skipping bikes that had a brand that didn't exist in the DB, but it breaks the 'dry' flag.  

here's the diff:
```
diff --git a/app/models/bike_csv_importer/bike_attrs.rb b/app/models/bike_csv_importer/bike_attrs.rb
index 375d90c..f496de4 100644
--- a/app/models/bike_csv_importer/bike_attrs.rb
+++ b/app/models/bike_csv_importer/bike_attrs.rb
@@ -54,6 +54,7 @@ class BikeCsvImporter

     def bike_attr_bike_brand_id(value)
       return unless value
+      value = 'Unknown' if value.match(/missing|unknown|[^a-zA-Z\d\s:]+/i)
       cached_bike_brand(value).try :id
     end

diff --git a/app/models/bike_csv_importer/cache.rb b/app/models/bike_csv_importer/cache.rb
index 33b36a6..f79dab1 100644
--- a/app/models/bike_csv_importer/cache.rb
+++ b/app/models/bike_csv_importer/cache.rb
@@ -11,7 +11,10 @@ class BikeCsvImporter
       if @bike_brand_cache.has_key? brand
         @bike_brand_cache[brand]
       else
-        @bike_brand_cache[brand] = BikeBrand.where('lower(brand) = ?', brand.downcase).first
+        bike_brand = BikeBrand.where('lower(brand) = ?', brand.downcase).first
+        bike_brand = BikeBrand.find_or_create_by_brand(brand) if bike_brand.nil?
+
+        @bike_brand_cache[brand] = bike_brand
       end
     end
```

**Comment by spacemunkay** [comment]
Unless you want to improve my changes, I'm cool with merging this and then I'll merge them in myself.  Thanks a ton! Great work!

**Comment by ilya-konanykhin** [comment]
I've updated the PR, now it has a `rake import:bikes:brands_csv[$file[,dry]]` task which will create any missing brand (all "unknown"-like are mapped to "Unknown" brand name). I see this as more robust and reusable, as it helps separate tasks thus making them single-responsibility.

**Comment by spacemunkay** [comment]
Tested it again, looks good! Merging!

**Pull request merged**
