### PR TITLE
Issue #105, #106: photo upload for User & Bike

### PR DESCRIPTION
**Pull request by ilya-konanykhin**
Images are managed via Paperclip and stored in public/system (the default way). In your set up it should be sufficient, but we always can migrate to S3 if necessary.

ExtJS isn't even working on my dev machine, so I skipped that part, if you don't mind.

Let me know if you need additional styling/validations/logic.

1 bike-form

2 bike-show

3 task-list

4 sign-up

### CODE REVIEW

**Comment by spacemunkay** [comment]
You rock!  Looks great.

We already talked about the minor issue with the new user's image clearing on invalid submission.  We decided to make some simple front end validations to help prevent users from submitting an invalid field.

**Comment by spacemunkay** [comment]
By the way, I discovered a bug that the username is not required by the backend on registration, but I think it should be?  (we can fix that in another PR)

**Comment by ilya-konanykhin** [comment]
All done.

**Comment by spacemunkay** [comment]
Sweet! Thanks for fixing a few extra issues along the way.  Merging!

**Pull request merged**
