### PR TITLE
dockerize!

### PR DESCRIPTION
**Pull request by spacemunkay**
* Updated to ruby 2.1
* Updated Gems
* Added needed Docker config files & scripts
* Updated guides
* Fixed bug in Seed Bike fixture
* Fixed bug where any 401 error resulted in signin redirect

### CODE REVIEW

**Comment by fspc** [comment]
Hi Jason,

I am not sure if you noticed, but I dockerized BikeShed back in December 2014, at https://github.com/fspc/bikeshed and I maintain a demo at http://bikeshed.wvcompletestreets.org (login info provided at http://bikebike.wvcompletestreets.org).

I will present Libre bike collective software at this years Bike!Bike! South East in Richmond, VA in two weeks.   Maybe I will see you there.

Good to observe you dockerizing, that is the way to go.

-Jonathan

**Comment by jnm** [comment]
:+1:

**Comment by brassmonkery** [comment]
@fspc I missed that, but totally wish I had seen it!  Ah well, at least it was good practice for me.  I'll add a link to the readme with your demo and alternative dockerfile.  

Hate I'll be missing your presentation, as I'm on the west coast now.   How do you find out about upcoming Bike!Bike! events?  Most of the Bike!Bike! sites I've seen are out of date.  Is there a mailing list  I can get on?

**Comment by spacemunkay** [comment]
@fspc I missed that, but totally wish I had seen it! Ah well, at least it was good practice for me. I'll add a link to the readme with your demo and alternative dockerfile.

Hate I'll be missing your presentation, as I'm on the west coast now. How do you find out about upcoming Bike!Bike! events? Most of the Bike!Bike! sites I've seen are out of date. Is there a mailing list I can get on?

**Comment by fspc** [comment]
@spacemunkay you can join TheThinkTank mailing list at http://lists.bikecollectives.org/listinfo.cgi/thethinktank-bikecollectives.org.

However, this year's regional Bike!Bike! Southeast in Richmond, VA was never announced by the organizers on that list, probably to keep the event manageable. 

The next international Bike!Bike! is in Detroit, MI, September 29 - October 2, http://thehubofdetroit.org/bikebike-2016/.   Will you be able to attend?

**Comment by spacemunkay** [comment]
@fspc Sweet, joined the list.  I'll do my best to make it to this years bikebike!

**Pull request merged**
